"""added a new column in savings for amount

Revision ID: b35e17325fea
Revises: 8f70a07b7ed3
Create Date: 2026-07-31 12:29:43.512290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35e17325fea'
down_revision = '8f70a07b7ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_goals', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
